name: Test EdgeXFoundry-Snap
on: push
jobs:
  test-snap:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: siggiskulason/edgex-test
        ref: master
    - name: testing snap install
      shell: bash 
      run: |
        echo "Running tests"
        ls -alR
        cd tests
        echo "2-Running tests"
        ls -alR
        . ./run-checkbox.sh
        
        
